---
# tasks file for poc-deploy
#- name: Setup Environment
#  include_tasks: traditional_setup.yml

- name: remove project directory if exists
  file:
    path: "{{ remote_project_dir }}"
    state: absent

- name: create project directory
  file:
    path: "{{ remote_project_dir }}"
    state: directory

# - name: copy jacoco required files to remote server
#   copy:
#     src: image-source
#     dest: "{{ remote_project_dir }}/"

- name: copy jacoco required files to remote server
  copy:
    src: yaml
    dest: "{{ remote_project_dir }}/"

- name: run k8s to deploy tomcat with war
  shell: "cd pipeline"
  shell: "{{ remote_project_dir }}/yaml/k8s.sh"