apiVersion: v1
kind: Service
metadata:
  name: petclinic-svc
spec:
  selector:
    app: petclinic-jenkins
  ports:
  - name: petclinic-svc1
    port: 8080
    targetPort: 8080
    nodePort: 32111
  - name: petclinic-svc2
    port: 6300
    targetPort: 6300
    nodePort: 32112
  type: NodePort

