apiVersion: v1  
kind: ReplicationController   
metadata:      
  name: petclinic-tester
spec:           
  replicas: 2
  selector:
    app:  petclinic-tester
  template:  
    metadata:  
     labels:      
      app: petclinic-tester  
    spec:
      containers:   
      - image: tomcat-jacoco #kubeguide/tomcat-app:v1 
        imagePullPolicy: Never
        name: petclinic-tester    
        ports:
        - containerPort:  8080
          name: http
          protocol: TCP
        - containerPort: 6300
          name: jacoco
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/local/tomcat/webapps/petclinic.war
          name: war
          subPath: petclinic.war
      volumes:
      - name: war
        hostPath:
          path: /Users/liujie/pipeline/